apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eco-superai

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: superai
    includeSelectors: false

resources:
  - namespace.yaml
  - priorityclass.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - cronjob.yaml

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"