receivers:
  otlp:
    protocols:
      grpc: { endpoint: "0.0.0.0:4317" }
      http: { endpoint: "0.0.0.0:4318" }
exporters:
  jaeger: { endpoint: "jaeger:14250", tls: { insecure: true } }
  logging: { loglevel: info }
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, logging]
