---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/service/instant-service
    eco-base/urn: urn:eco-base:k8s:core:service:instant-service:sha256-99e46ecd4df70892050154f054c863878906bebe476e96fe5a61c24a18a72576
  labels:
    app.kubernetes.io/app.kubernetes.io/component: data
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: instant-system
    app.kubernetes.io/part-of: machine-native-ops
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    governance.machinenativeops.io/charter-version: 2.0.0
  name: instant-service
  namespace: platform-03
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: instant-system
  type: ClusterIP
