apiVersion: v1
kind: Service
metadata:
  name: observops-engine
  namespace: eco-observops
  labels:
    app.kubernetes.io/name: observops-engine
    app.kubernetes.io/instance: observops-engine-prod
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/component: engine
    eco-base/platform: platform-observops
    eco-base/environment: production
    governance.io/managed: "true"
  annotations:
    eco-base/uri: "eco-base://k8s/platform-observops/service/observops-engine"
    eco-base/urn: "urn:eco-base:k8s:platform-observops:service:observops-engine:gl.observ-ops.platform"
spec:
  selector:
    app.kubernetes.io/name: observops-engine
    app.kubernetes.io/component: engine
  ports:
    - name: http
      port: 8094
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9094
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
