apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eco.fullname" . }}
  namespace: {{ .Values.namespace | default "indestructibleeco" }}
  labels:
    {{- include "eco.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: "indestructibleeco-sa@indestructibleeco.iam.gserviceaccount.com"
automountServiceAccountToken: true
