---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/service/govops-engine
    eco-base/urn: urn:eco-base:k8s:core:service:govops-engine:sha256-7f939fd77f7246a50ca51182f40dec59d8a7ad27ffa59f37f8e51a492c04d0b8
  labels:
    app.kubernetes.io/component: engine
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: govops-engine
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/owner: eco-system
    eco-base/platform: core
    governance.io/managed: 'true'
  name: govops-engine
  namespace: eco-govops
spec:
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: engine
    app.kubernetes.io/name: govops-engine
  type: ClusterIP
