apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eco-govops-dev

namePrefix: dev-

resources:
  - ../../base

patches:
  # --- Engine: single replica, lower resources ---
  - target:
      kind: Deployment
      name: govops-engine
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GOVOPS_ENV
          value: development
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GOVOPS_LOG_LEVEL
          value: DEBUG

  # --- HPA: 1-2 replicas ---
  - target:
      kind: HorizontalPodAutoscaler
      name: govops-engine-hpa
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2

configMapGenerator:
  - name: govops-env-override
    literals:
      - GOVOPS_ENV=development
      - GOVOPS_LOG_LEVEL=DEBUG
      - GOVOPS_WORKERS=1
