---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/secret/machine-native-ops-secrets
    eco-base/urn: urn:eco-base:k8s:core:secret:machine-native-ops-secrets:sha256-81539c31ea68b0af705b773541bd467b9b821bd372cbf6839fd6f4f038552362
  labels: {}
  name: machine-native-ops-secrets
  namespace: platform-03
stringData:
  api-secret-key: change-me-in-production-use-32-chars
  api-signing-key: change-me-in-production-use-64-chars
  aws-access-key-id: ''
  aws-region: us-east-1
  aws-secret-access-key: ''
  database-password: change-me-in-production
  database-url: postgresql://user:password@postgres:5432/machineops
  database-username: machineops_user
  encryption-key: change-me-32-byte-encryption-key-123456
  pagerduty-api-key: ''
  prometheus-basic-auth-password: change-me-in-production
  prometheus-basic-auth-username: prometheus
  signing-key: change-me-64-byte-signing-key-1234567890123456
  slack-webhook-url: ''
  smtp-from: noreply@machinenativeops.com
  smtp-host: smtp.gmail.com
  smtp-password: ''
  smtp-port: '587'
  smtp-username: ''
type: Opaque
