apiVersion: v1
kind: Service
metadata:
  name: seccompops-engine
  namespace: eco-seccompops
  labels:
    app.kubernetes.io/name: seccompops-engine
    app.kubernetes.io/part-of: seccompops-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8095
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9095
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: seccompops-engine
