---
apiVersion: v1
data:
  JAEGER_AGENT_HOST: jaeger-agent.istio-system.svc.cluster.local
  JAEGER_AGENT_PORT: '6831'
  JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  JAEGER_REPORTER_LOG_SPANS: 'true'
  JAEGER_REPORTER_MAX_QUEUE_SIZE: '1000'
  JAEGER_SAMPLER_PARAM: '0.1'
  JAEGER_SAMPLER_TYPE: probabilistic
  JAEGER_TAGS: environment=production,service=machine-native-ops
  OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger-agent.istio-system.svc.cluster.local
  OTEL_EXPORTER_JAEGER_AGENT_PORT: '6831'
  OTEL_RESOURCE_ATTRIBUTES: service.name=machine-native-ops,deployment.environment=production
  OTEL_SERVICE_NAME: machine-native-ops
kind: ConfigMap
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/configmap/jaeger-config
    eco-base/urn: urn:eco-base:k8s:core:configmap:jaeger-config:sha256-7e56f281d85b3d75e92c9bf2f984787651b268f192065ee6a33c45e8fc2b2b9d
  labels:
    app.kubernetes.io/name: jaeger
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    environment: production
  name: jaeger-config
  namespace: production
---
apiVersion: v1
data:
  tracing.yaml: "enabled: true\nprovider: jaeger\nsampling:\n  type: probabilistic\n\
    \  rate: 0.1\n  environment: production\njaeger:\n  agent:\n    host: jaeger-agent.istio-system.svc.cluster.local\n\
    \    port: 6831\n  collector:\n    endpoint: http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces\n\
    \  sampler:\n    type: probabilistic\n    param: 0.1\n  reporter:\n    logSpans:\
    \ true\n    maxQueueSize: 1000\n    flushInterval: 1s\npropagators:\n  - jaeger\n\
    \  - b3\n  - trace-context\ntags:\n  environment: production\n  service: machine-native-ops\n\
    \  version: v1\nheaders:\n  trace:\n    - uber-trace-id\n    - x-request-id\n\
    \    - x-b3-traceid\n    - x-b3-spanid\n    - x-b3-parentspanid\n    - x-b3-sampled"
kind: ConfigMap
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/configmap/tracing-config
    eco-base/urn: urn:eco-base:k8s:core:configmap:tracing-config:sha256-7ac4f2bf8e076c0988b094c085e4ce274661500e31f0da2b5d87789fad2b62dd
  labels:
    app.kubernetes.io/name: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    environment: production
  name: tracing-config
  namespace: production
