global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - "alerts.yml"
scrape_configs:
  - job_name: "api-service"
    static_configs:
      - targets: ["api-service.indestructibleeco:3000"]
  - job_name: "ai-service"
    static_configs:
      - targets: ["ai-service.indestructibleeco:8001"]
