---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    eco-base/uri: eco-base://k8s/core/ingress/quantumflow-ingress
    eco-base/urn: urn:eco-base:k8s:core:ingress:quantumflow-ingress:sha256-fd7539923864eb0d9555e296f711a5a118557b86fc833d6684b28d6dc65a338d
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rate-limit: '100'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  labels: {}
  name: quantumflow-ingress
  namespace: quantumflow
spec:
  rules:
  - host: quantumflow.example.com
    http:
      paths:
      - backend:
          service:
            name: quantumflow-backend
            port:
              number: 8000
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: quantumflow-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - quantumflow.example.com
    secretName: quantumflow-tls
