---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/ingress/quantumflow-ingress
    eco-base/urn: urn:eco-base:k8s:core:ingress:quantumflow-ingress:sha256-317173c9baeeb8c67f563869165b6d69a2987e272f4dfb8c1ed03422b8b67463
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rate-limit: '100'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: quantumflow-ingress
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/owner: eco-system
    eco-base/platform: core
  name: quantumflow-ingress
  namespace: quantumflow
spec:
  rules:
  - host: quantumflow.example.com
    http:
      paths:
      - backend:
          service:
            name: quantumflow-backend
            port:
              number: 8000
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: quantumflow-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - quantumflow.example.com
    secretName: quantumflow-tls
