---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/service/elasticsearch-search-service
    eco-base/urn: urn:eco-base:k8s:core:service:elasticsearch-search-service:sha256-b68c34e07f666d22529928da982ba49af375b14218c3294f8614ca38fda2e0d8
  labels:
    app.kubernetes.io/app.kubernetes.io/component: search
    app.kubernetes.io/name: elasticsearch-search-system
    app.kubernetes.io/part-of: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: elasticsearch-search-service
  namespace: platform-03
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: elasticsearch-search-system
  type: ClusterIP
