apiVersion: v1
kind: Service
metadata:
  name: dataops-engine
  namespace: eco-dataops
  labels:
    app.kubernetes.io/name: dataops-engine
    app.kubernetes.io/part-of: dataops-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8093
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9093
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: dataops-engine
