---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/service/dataops-engine
    eco-base/urn: urn:eco-base:k8s:core:service:dataops-engine:sha256-5a5abd610967958d878215a96ec78930656a72fd9733e5ce57c5887d32f25e01
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: dataops-engine
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/owner: eco-system
    eco-base/platform: core
  name: dataops-engine
  namespace: eco-dataops
spec:
  ports:
  - name: http
    port: 8093
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 9093
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: dataops-engine
  type: ClusterIP
