apiVersion: v1
kind: ResourceQuota
metadata:
  name: superai-quota
  namespace: eco-superai
  labels:
    app.kubernetes.io/name: superai-platform
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "10"
    secrets: "20"
    configmaps: "20"
    replicationcontrollers: "0"
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: Exists