---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/note: TEMPLATE â€” replace placeholders before applying
    eco-base/owner: platform-team
    eco-base/uri: eco-base://k8s/core/secret/argocd-repo-eco-base
    eco-base/urn: urn:eco-base:k8s:core:secret:argocd-repo-eco-base:sha256-1958ac65c03c8b87c4914510fd950179ddcc8b957ce3a9e8fb24988fd74e1246
  labels:
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: argocd-repo-eco-base
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    argocd.argoproj.io/secret-type: repository
    eco-base/environment: development
    eco-base/owner: eco-system
    eco-base/platform: core
  name: argocd-repo-eco-base
  namespace: argocd
stringData:
  type: git
  url: https://github.com/indestructibleorg/eco-base
type: Opaque
