---
apiVersion: v1
data:
  CIRCLECI_RUNNER_MODE: single-task
  CIRCLECI_RUNNER_NAME: eco-base-gke-runner
  CIRCLECI_RUNNER_RESOURCE_CLASS: eco/base
  CLEANUP_WORKSPACE: 'true'
  LOG_FORMAT: json
  LOG_LEVEL: info
  POD_CHECK_INTERVAL: 30s
  POD_TIMEOUT: 10m
  WORKING_DIRECTORY: /tmp/circleci-workspace
kind: ConfigMap
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/configmap/circleci-agent-config
    eco-base/urn: urn:eco-base:k8s:core:configmap:circleci-agent-config:sha256-a2ededce7af41376873f8dd2d0eab7e3d12a936f1261c62cbb54728c43a550c5
  labels:
    app: circleci-runner
  name: circleci-agent-config
  namespace: circleci-runner
