---
apiVersion: v1
data:
  CIRCLECI_RUNNER_MODE: single-task
  CIRCLECI_RUNNER_NAME: eco-base-gke-runner
  CIRCLECI_RUNNER_RESOURCE_CLASS: eco/base
  CLEANUP_WORKSPACE: 'true'
  LOG_FORMAT: json
  LOG_LEVEL: info
  POD_CHECK_INTERVAL: 30s
  POD_TIMEOUT: 10m
  WORKING_DIRECTORY: /tmp/circleci-workspace
kind: ConfigMap
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/configmap/circleci-agent-config
    eco-base/urn: urn:eco-base:k8s:core:configmap:circleci-agent-config:sha256-df581c3238296b0dcac33da0b66e77d467ec68000d7e7f8a107be9a68758517c
  labels:
    app: circleci-runner
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: circleci-agent-config
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/owner: eco-system
    eco-base/platform: core
  name: circleci-agent-config
  namespace: circleci-runner
