---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/secret/circleci-runner-secrets
    eco-base/urn: urn:eco-base:k8s:core:secret:circleci-runner-secrets:sha256-b78c0f2a2fc66c18baea3b7560b25f9384efa967de7c7369b72d0e8eb926a631
  labels:
    app: circleci-runner
  name: circleci-runner-secrets
  namespace: circleci-runner
stringData:
  CIRCLECI_API_TOKEN: REPLACE_WITH_CIRCLECI_API_TOKEN
  CIRCLECI_RUNNER_TOKEN: REPLACE_WITH_CIRCLECI_RUNNER_TOKEN
type: Opaque
