---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/secret/circleci-runner-secrets
    eco-base/urn: urn:eco-base:k8s:core:secret:circleci-runner-secrets:sha256-11393f5451ef15528ae6bfaa44dd6b9d0e03d2d50a010ee4cd2584453ab1aa3f
  labels:
    app: circleci-runner
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: circleci-runner-secrets
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/owner: eco-system
    eco-base/platform: core
  name: circleci-runner-secrets
  namespace: circleci-runner
stringData:
  CIRCLECI_API_TOKEN: REPLACE_WITH_CIRCLECI_API_TOKEN
  CIRCLECI_RUNNER_TOKEN: REPLACE_WITH_CIRCLECI_RUNNER_TOKEN
type: Opaque
