---
apiVersion: v1
data:
  AUDIT_TRAIL_REQUIRED: 'true'
  CONTINUE_ON_ERROR: 'false'
  ENVIRONMENT: production
  GOVERNANCE_MODE: strict
  LOG_LEVEL: info
  VALIDATION_REQUIRED: 'true'
kind: ConfigMap
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/configmap/machine-native-ops-config
    eco-base/urn: urn:eco-base:k8s:core:configmap:machine-native-ops-config:sha256-3d9682e97eaa1e8ea794d4725da2105c370265d307455ebb35eb9af088956ef3
  labels:
    app.kubernetes.io/app.kubernetes.io/component: config
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: machine-native-ops
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    governance.machinenativeops.io/charter-version: 2.0.0
  name: machine-native-ops-config
  namespace: platform-03
