---
apiVersion: v1
data:
  AUDIT_TRAIL_REQUIRED: 'true'
  CONTINUE_ON_ERROR: 'false'
  ENVIRONMENT: production
  GOVERNANCE_MODE: strict
  LOG_LEVEL: info
  VALIDATION_REQUIRED: 'true'
kind: ConfigMap
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/configmap/machine-native-ops-config
    eco-base/urn: urn:eco-base:k8s:core:configmap:machine-native-ops-config:sha256-86b41da3409126b562fd459eceee3326f0f5a11a74dc1660db0823738fecadf3
  labels:
    app.kubernetes.io/app.kubernetes.io/component: config
    app.kubernetes.io/name: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: machine-native-ops-config
  namespace: platform-03
