---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/secret/machine-native-ops-secrets
    eco-base/urn: urn:eco-base:k8s:core:secret:machine-native-ops-secrets:sha256-bba5ac4c92302688542000a583729fb896cca6fe0f9708b2ffae875a7baeeddf
    governance.machinenativeops.io/secret-type: placeholder
  labels:
    app.kubernetes.io/app.kubernetes.io/component: secret
    app.kubernetes.io/name: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: machine-native-ops-secrets
  namespace: platform-03
stringData:
  API_KEY: placeholder-replace-with-vault
  DATABASE_PASSWORD: placeholder-replace-with-vault
  GL_TOKEN: placeholder-replace-with-vault
type: Opaque
