---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/secret/machine-native-ops-secrets
    eco-base/urn: urn:eco-base:k8s:core:secret:machine-native-ops-secrets:sha256-a892463ed0306d5e4198cb8e2aafb7b7c0936ca5a87b4397caecd9da95cd564c
    governance.machinenativeops.io/secret-type: placeholder
  labels:
    app.kubernetes.io/app.kubernetes.io/component: secret
    app.kubernetes.io/component: eco-component
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: machine-native-ops
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/governance: aligned
    eco-base/owner: eco-system
    eco-base/part-of: eco-base
    eco-base/platform: core
    governance.machinenativeops.io/charter-version: 2.0.0
  name: machine-native-ops-secrets
  namespace: platform-03
stringData:
  API_KEY: placeholder-replace-with-vault
  DATABASE_PASSWORD: placeholder-replace-with-vault
  GL_TOKEN: placeholder-replace-with-vault
type: Opaque
