---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/ingress/gl-semantic-core-ingress
    eco-base/urn: urn:eco-base:k8s:core:ingress:gl-semantic-core-ingress:sha256-08feaf48daadd6c61e804de50390641116dded3046e34568be31d4e161359d71
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers "ECO-Platform:
      semantic-core";

      more_set_headers "ECO-Version: v1.0.0";

      '
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,ECO-Platform,ECO-Version
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/limit-connections: '1000'
    nginx.ingress.kubernetes.io/limit-rps: '100'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
  labels:
    app.kubernetes.io/name: semantic-core
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    platform: gl-platform-services
  name: gl-semantic-core-ingress
  namespace: gl-platform-semantic-core
spec:
  rules:
  - host: semantic-core.gl-enterprise-architecture.example.com
    http:
      paths:
      - backend:
          service:
            name: gl-semantic-core-service
            port:
              number: 80
        path: /semantic(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: gl-semantic-core-service
            port:
              number: 80
        path: /health
        pathType: Exact
      - backend:
          service:
            name: gl-semantic-core-service
            port:
              number: 9091
        path: /metrics
        pathType: Exact
  - host: api.semantic.gl.example.com
    http:
      paths:
      - backend:
          service:
            name: gl-semantic-core-service
            port:
              number: 80
        path: /v1(/|$)(.*)
        pathType: Prefix
