---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/service/gl-spec-core-service
    eco-base/urn: urn:eco-base:k8s:core:service:gl-spec-core-service:sha256-08b2ce07bef56a624aa35aa3558700bc3bef1d3468930c39b663086847a92c9e
    prometheus.io/port: '9091'
    prometheus.io/scrape: 'true'
  labels:
    app.kubernetes.io/name: spec-core
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    gl.service/semantic.core: 'true'
    platform: gl-platform-services
  name: gl-spec-core-service
  namespace: gl-platform-spec-core
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app.kubernetes.io/name: spec-core
    version: v1.0.0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/service/gl-spec-core-external
    eco-base/urn: urn:eco-base:k8s:core:service:gl-spec-core-external:sha256-1c34f64e7022b794b9ce6e0327ad17320f9a8f0f25d5632b9c475245f8cdbe5f
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: alb
  labels:
    app.kubernetes.io/name: spec-core-external
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    platform: gl-platform-services
  name: gl-spec-core-external
  namespace: gl-platform-spec-core
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spec-core
    version: v1.0.0
  type: LoadBalancer
